services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: challenge
    ports:
      - 5432:5432
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql